#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#Load modules
module load salmon/1.1.0
r14=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz
r15=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz
r16=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz
r24=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_2.fastq.gz
r25=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_2.fastq.gz
r26=/projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_2.fastq.gz


salmon alevin -l ISR -p 10 -1 $r14 $r15 $r16 -2 $r24 $r25 $r26 -i /projectnb/bf528/users/hedgehog_2022/project_4/Data_curator/salmon_index/ -o salmon_newindex_strict --tgMap /projectnb/bf528/users/hedgehog_2022/project_4/Data_curator/other_output_files/map.tsv --whitelist /projectnb/bf528/users/hedgehog_2022/project_4/Data_curator/other_output_files/whitelist_strict_filter.csv --end 5 --barcodeLength 19 --umiLength 6 --dumpMtx   
echo "Job finished $(date +%F)"
