#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#Load modules 
module unload anaconda3
module load python3/3.6.5
module load umitools/1.0.0


#Merging the files

zcat /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz > UMI.fastq

#printing the bar codes
awk '{if (NR%4==2) {print substr($1,1,19)}}' UMI.fastq | sort | uniq -c > white_list.txt
echo "Job finished $(date +%F)" 


