#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#Loading module

module load salmon/1.1.0

cat gencode.v40.transcripts.fa.gz GRCh38.primary_assembly.genome.fa.gz > gentrome.fa.gz

salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode

#without decoy
salmon index -i salmon_index -k 31 --gencode -p 10 -t gencode.v40.transcripts.fa

echo "Job finished $(date +%F)"



