#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#Load modules
module unload anaconda3
module load python3/3.6.5
module load umitools/1.0.0



#printing the bar codes

grep ">" /projectnb/bf528/users/hedgehog_2022/project_4/Data_curator/gencode.v40.transcripts.fa | awk -F'|' '{print $1"\t"$2}' | cut -c 2- > map.tsv
echo "Job finished $(date +%F)"




